# Thanks be to - https://mmistakes.github.io/minimal-mistakes/docs/configuration/
#  and - https://help.github.com/en/articles/repository-metadata-on-github-pages
repository: S0AndS0/100-days-of-code
